spring.application.name: customers-service
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://customers-db:3306/customers?useSSL=false
    username: root
    password: petclinic
