spring.h2.console.enabled=true
spring.h2.console.settings.webAllowOthers=true
spring.datasource.password=${DB_PASSWORD}
jhipster.security.authentication.jwt.base64-secret=c2VjcmV0LWRlbW8tZG8tbm90LXVzZQ==
