package dev.scg.cli;

import java.io.IOException;
import java.io.InputStream;
import java.util.Optional;
import java.util.Properties;

/**
 * The version of the running tool, read from the {@code pom.properties} Maven writes into every
 * packaged jar. Outside a packaged jar (tests, an IDE run from {@code target/classes}) that file
 * doesn't exist and the version is unknown — reported as such rather than guessed.
 * <p>
 * Chosen over the manifest's {@code Implementation-Version} because {@code pom.properties} is
 * already generated by the default build, with no plugin configuration to maintain. The release
 * workflow checks that the published jar reports exactly the released version.
 */
public final class Version {

    static final String POM_PROPERTIES = "/META-INF/maven/dev.scg/spring-config-guard/pom.properties";

    private Version() {
    }

    public static Optional<String> current() {
        return fromResource(POM_PROPERTIES);
    }

    /** Line printed by {@code --version}. */
    public static String describe() {
        return current()
                .map(version -> "spring-config-guard " + version)
                .orElse("spring-config-guard (version unknown: not running from a packaged jar)");
    }

    static Optional<String> fromResource(String resource) {
        try (InputStream in = Version.class.getResourceAsStream(resource)) {
            if (in == null) {
                return Optional.empty();
            }
            Properties properties = new Properties();
            properties.load(in);
            String version = properties.getProperty("version");
            return version == null || version.isBlank() ? Optional.empty() : Optional.of(version.strip());
        } catch (IOException e) {
            return Optional.empty();
        }
    }
}
