server:
  port: 8080

spring:
  application:
    name: demo-service
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
